global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'trading_system'
    static_configs:
      - targets: ['localhost:8000']
  - job_name: 'frontend'
    static_configs:
      - targets: ['localhost:3000']
  - job_name: 'database'
    static_configs:
      - targets: ['localhost:5432']
